In [25]:
import time
start = time.time()
import numpy as np
import sys
import pdb




A = np.array([[5.2,3,0.5,1,2],[3,6.3,-2,4,0],[0.5,-2,8,-3.1,3],[1,4,-3.1,7.6,2.6],[2,0,3,2.6,15]])


b = np.array([[2],[5],[3],[1],[1]])




def lowerMatrix(L,b): #forward
    n = L.shape[0] # size of matrix
    y = np.zeros(n) # creat matrix n*1 and zero elements
    for i in range(n):
        y[i] = (b[i]- np.sum([L[i,j]*y[j] for j in range(i)]))/L[i,i] #formula for y_i in Ly=b
    return y

def upperMatrix(U,y):  #backward
    n = U.shape[0] # size of matrix
    x = np.zeros(n) # creat matrix n*1 and zero elements
    for i in range(n-1,-1,-1): # i = n-1 to 0
        x[i] = (y[i]- np.sum([U[i,j]*x[j] for j in range(i+1,n)]))/U[i,i] #formula for x_i in Ux=y
    return x


def function(A):
    B = A.copy()
    n = B.shape[0]
    intch = np.zeros(n, dtype=int) #for PLU
    for k in range(n-1): # n-1 because there is no need to use function for last row
        amax = np.max(np.absolute(B[k:n,k]))  #k:n --> columns k to n
        m = np.argmax(np.absolute(B[k:n,k])) + k # +k because index will start from k (k:n)
        # now : amax = A[m,k]  --> row: m and column: k
        if amax == 0:
            print("Matrix is Singular!")
            return False
        else:
            intch[k] = m
            if k!=m:
                B[[k,m]] = B[[m,k]] #change row m with row k
            B[k+1:n,k] = B[k+1:n,k]/B[k,k] #formula for get ZARIB ha
            #A[k+1:n,k] means every row of A in Columns k from row k+1 to n
            for i in range(k+1,n):
                B[i,k+1:n] = B[i,k+1:n] - B[i,k]*B[k,k+1:n]

    if B[n-1,n-1] == 0:
        print("Matrix is Singular!")
        return False
    else:
        intch[n-1] = n-1

    return B , intch

def LU(A):
    if function(A):
        B , intch = function(A)
        n = B.shape[0]
        U = np.triu(B)
        L = B - U + np.eye(n)

        P = np.eye(n)
        for k in range(n):
            m = intch[k]
            P[[k, m]] = P[[m, k]]

        return P,L,U
    else:
        return False

def solve(L,U,b):
    y = lowerMatrix(L, b)
    x = upperMatrix(U, y)
    return x


print ("A:")
print (A)


p, L,U = LU(A)


print ("L:\n", L)
print ("U:\n", U)

print ("L*U:\n", np.dot(L, U))

x = solve(L, U, b)

print("\nLes solutions du système sont : ",x)

end = time.time()
print("\nTemps d'exécution : ",(end - start) * 10**3," ms")

A:
[[ 5.2  3.   0.5  1.   2. ]
 [ 3.   6.3 -2.   4.   0. ]
 [ 0.5 -2.   8.  -3.1  3. ]
 [ 1.   4.  -3.1  7.6  2.6]
 [ 2.   0.   3.   2.6 15. ]]
L:
 [[ 1.          0.          0.          0.          0.        ]
 [ 0.57692308  1.          0.          0.          0.        ]
 [ 0.09615385 -0.50084175  1.          0.          0.        ]
 [ 0.19230769  0.74915825 -0.21771745  1.          0.        ]
 [ 0.38461538 -0.25252525  0.32763365  0.78865888  1.        ]]
U:
 [[ 5.2         3.          0.5         1.          2.        ]
 [ 0.          4.56923077 -2.28846154  3.42307692 -1.15384615]
 [ 0.          0.          6.80576599 -1.48173401  2.22979798]
 [ 0.          0.          0.          4.52066665  3.56526391]
 [ 0.          0.          0.          0.         10.39706003]]
L*U:
 [[ 5.20000000e+00  3.00000000e+00  5.00000000e-01  1.00000000e+00
   2.00000000e+00]
 [ 3.00000000e+00  6.30000000e+00 -2.00000000e+00  4.00000000e+00
   0.00000000e+00]
 [ 5.00000000e-01 -2.00000000e+00  8.000