In [17]:
import time
start = time.time()
import numpy as np

#Saisie de la matrice A (DOIT ETRE INVERSIBLE!)
A = np.array([[5.2,3,0.5,1,2],[3,6.3,-2,4,0],[0.5,-2,8,-3.1,3],[1,4,-3.1,7.6,2.6],[2,0,3,2.6,15]])
print("La matrice A est :\n",A)

#Décomposition de A
def householder(A):
    n, _ = A.shape
    x = A[:,0].reshape(n,1)
    e1 = np.zeros((n,1))
    e1[0] = 1.
    v = np.sign(x[0]) * np.linalg.norm(x) * e1 + x
    P = np.eye(n) - 2 * v.dot(v.T)/v.T.dot(v)
    return P

def qr_decomposition(A):
    n, _ = A.shape
    P = np.zeros((n-1,n,n))
    R = A
    for i in range(n-1):
        P[i] = np.eye(n)
        P[i,i:,i:] = householder(R[i:,i:])
        print(f'Itération {i}', np.round(P[i].dot(R), 1))
        R = P[i].dot(R)
    Q_T = np.eye(n)
    for i in range(n-1):
        Q_T = P[i].dot(Q_T)
    Q = Q_T.T
    return Q, R
    
#Affichage de Q et R
Q,R = qr_decomposition(A)
print("\nQ = ",Q)
R_int = R.astype(int)
print("\nR = ",R_int)
print("\nQR = ",np.dot(Q,R))

#Saisie du vecteur b
b = np.array([[2],[5],[3],[1],[1]])

#Résolution des deux systèmes
def Résolution(Q,R,b):
    Q = np.array(Q,float)
    R = np.array(R,float)
    b = np.array(b,float)
    n,_ = np.shape(Q)
    x = np.zeros(n)
    #Résolution du système Qy = b
    y = np.dot(np.transpose(Q),b) #Q^-1 = Q^t car Q est orthogonale
    #Résolution du système triangulaire supérieur Rx = y (Remontée)
    for i in range(n-1,-1,-1):
        somme_j = 0
        for j in range(i+1,n):
            somme_j += R[i,j] * x[j]
        x[i] = (y[i] - somme_j) / R[i,i]
    return x, y

x, y = Résolution(Q,R,b)
np.ceil(y)
np.ceil(x)
print("y = ",y)
print("x = ",x)
end = time.time()
print("\nTemps d'exéuction : ",(end - start) * 10**3," ms")

La matrice A est :
 [[ 5.2  3.   0.5  1.   2. ]
 [ 3.   6.3 -2.   4.   0. ]
 [ 0.5 -2.   8.  -3.1  3. ]
 [ 1.   4.  -3.1  7.6  2.6]
 [ 2.   0.   3.   2.6 15. ]]
Itération 0 [[-6.4 -5.8 -0.5 -4.4 -6.9]
 [ 0.   4.  -2.3  2.6 -2.3]
 [ 0.  -2.4  8.  -3.3  2.6]
 [ 0.   3.2 -3.2  7.1  1.8]
 [ 0.  -1.5  2.8  1.7 13.5]]
Itération 1 [[-6.4 -5.8 -0.5 -4.4 -6.9]
 [-0.  -5.9  7.3 -6.6  5.1]
 [ 0.   0.   5.7 -1.1  0.8]
 [-0.  -0.  -0.1  4.1  4.3]
 [ 0.   0.   1.4  3.1 12.3]]
Itération 2 [[-6.4 -5.8 -0.5 -4.4 -6.9]
 [-0.  -5.9  7.3 -6.6  5.1]
 [-0.  -0.  -5.8  0.4 -3.6]
 [-0.  -0.   0.   4.1  4.3]
 [ 0.  -0.   0.   3.3 11.8]]
Itération 3 [[ -6.4  -5.8  -0.5  -4.4  -6.9]
 [ -0.   -5.9   7.3  -6.6   5.1]
 [ -0.   -0.   -5.8   0.4  -3.6]
 [ -0.    0.   -0.   -5.2 -10.7]
 [  0.    0.    0.    0.    6.6]]

Q =  [[-0.80924663  0.29273079  0.3540929   0.15140407 -0.33335206]
 [-0.46687306 -0.60754912 -0.36920102  0.36862956  0.37512194]
 [-0.07781218  0.41701689 -0.84644976  0.06227811 -0.31573157]
 [-0.15